#pragma once

#include <Arduino.h>

void imuDataOutCmdSend(int onOff);
void usb5vChange_Check();
int DecodeLZ(unsigned char* src, unsigned char* dst, int opt);
void Exec_Download(String msg);
void Log_Control_Step();
void reelAllOff_SendControl();
void lmLongWireCheck_Start();
void lmLongWireCheck_Stop();
void checkBbnCcwCheck();
void lmWireControl_Start();
void lmWireControl_End();
void lmWireControl_Stop();
void lmWireControl();
void wat_isrLogOut();
void t1ms_Process_Exec();
void t10ms_Process_Exec();
void t100ms_Process_Exec();
void t500ms_Process_Exec();
void t1sec_Process_Exec();
void sendCmdSts_MainPwrOn();
void logUartRecvParsing();
void logRecvHandler();
void extIOuartRecvHandler();
void imuInterval_Measure();
void nowRecvHandler();
void uartRecvParsing();
void uartRecvHandler();
String anaVrtMotCmd(String msg);
void ana_SetDataSave(String msg);
String anaBtnLedCmd(String msg);
String anaDevSetReq(String msg);
String anaDevSet_MainMotor_AutoSet(String msg);
String anaDevFunctionReq(String msg);
String anaDevFunc_wireAging(String msg);
void mainMot_MinOut_AutoSet_Start(String msg);
void mainMot_MinOut_AutoSet_Stop(String msg);
void torqMotor_DefaultOut();
void mainMot_MinOut_AutoSet_Control1_Period();
void mainMot_MinOut_AutoSet_Control2_Time();
void mainMot_MinOut_AutoSet_Control3_36PulseTime();
void stbyTorqOffControl_Start();
void stbyTorqOffControl_Stop(int flag);
void stbyTorqOff_ReqCheck();
void stbyTorqOff_Control();
void wireAging_Test_Start(String msg);
unsigned short splitTextToStrings(String msg, String *s);
void wireAging_Test_Stop(String msg);
void wireAging_Test_Control();
void boardLed_Control();
void read_input_1ms();
void read_input_10ms();
void read_input_100ms();
void eeprom_test();
void subAc_Control_atReset();
short setConfig();
void ioLedOffSetting();
void ioPinSetting();
void wat_PidParaSet(String msg);
void wat_HookRandCheckExec();
void wat_PidStart_TargetSet(short _targetDist);
void wat_PidStop();
void IRAM_ATTR ISR_onTimerHandler();
void IRAM_ATTR ISR_encIntrHandle();
void spi_out(int _pin, int _val);
void system_counter();
int getBoardType();

extern int g_ProcStatus;
extern int pwrOn1stCmdSendFlag;
extern int handEncCnt;
extern volatile int rcved_flag;
extern int rcved_Seq;
extern String rcvApMsg;
extern String rcvApMsg_Save;
extern unsigned long pulseWidthMs;
