#pragma once

#include <Arduino.h>

void apPatternReq_Bite_Hold();
void testHand();
void diagInputMonitor();
void diagInputMotorSensorAllOff();
int randomNum(int min, int max);
void biteType_TorqSet(int _fishKind);
int fishKind_autoFromBreak(int breakval);
int fishKind_FromKg(double fishKg);
void execWave_servo();
void execWave_torque();
void execWave_bbn();
void execWave_bbn_Torq();
void execWave_torq_bbn_Start();
void execWave_torq_bbn();
void execBite_servo();
void execBite_torque_justTarget();
void execBite_torque_incTarget();
void rdyincTorq_Stop();
void rdyincTorq_Start();
void setReadyTorque_incTarget(int targetTorq, int incTime, int incTorq);
void setReadyPosition_Start(int option);
void execReady_TorqControl();
void execBite_BldcStart();
void execBite_BldcControl();
void execBite_torquewf_Start(int reqCnt);
void execBite_torquewf_Control(int reqCnt);
void execBite_ptn1_Start();
void execBite_ptn2_Start();
void execBite_ptn3_Start();
void execBite_ptn_Flag_Clear();
void exeBiteFlag_Clr_check();
void execBite_ptn_Stop();
void execBite_ptn1_Control();
void execBite_ptn2_Control();
void execBite_ptn3_Control();
void execHit_BldcStart();
void execHit_1st_BldcControl();
void execHiting();
void execHit_FightBldcStop();
void execHit_FightBldcStart(unsigned _ptn);
void execHit_FightBldcControl();
void execHit_ResistRandomStart();
void execHit_ResistRandom_ToCheck();
void execHit_HoldServo();
void execHit_ResistTorqStop();
void execHit_ResistTorqStart();
void execHit_ResistTorqControl();
void execHit_Holdon_BldcStart();
void execHit_Holdon_BldcControl();
void execHoldon_ptn1_Start();
void execHoldon_ptn1_BldcControl();
void Check_HoldOnPtn_AllClr();
void execHit_HoldOn_TorqStop();
void execHit_HoldOn_TorqStart();
void execHit_HoldOn_TorqControl();
void execHit_SetBreakOnceStart();
void send_breakmot(int _val);
void execHit_BreakStop();
void execHit_BreakStart();
void execHit_BreakControl();
void execHit_BreakDecStop();
void execHit_BreakDecStart();
void execHit_BreakDecControl();
void execFastHold_SetVal();
void execFastHold_Start();
void execFastHold_Control();
void execButtonCombo_SetVal();
void execButtonCombo_Start();
void execButtonCombo_Control();
void execRanding_SetVal();
void execRanding_Start();
void execRanding_Control();
void setAfter1sec_LogOut_Start();
void setAfterTo_LogOut_Control();
void execSuccessFail();
void execPointUp();
void execEnd();

extern unsigned int wave_tq_step;
extern unsigned int wave_bbn_tq_step;
extern unsigned int wave_bbn_step;
extern unsigned int wave_torq_bbn_step;
extern unsigned int bite_jt_step;
extern unsigned int bite_it_step;
extern unsigned int rdy_incStep;
extern unsigned int bite_bldc_step;
extern unsigned int bite_wf_step;
extern unsigned int hit_BldcStep;
extern unsigned int bbnFight_step;
extern unsigned int hitResistRdStep;
extern unsigned int hit_resist_step;
extern unsigned int holdon_bldc_step;
extern unsigned int hit_holdon_step;
extern unsigned int hit_brk_step;
extern unsigned int fastHoldStep;
extern unsigned int btnComboStep;
extern unsigned int randingStep;
extern unsigned int exeTo1secLog;
